version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'sunday'
    commit-message:
      prefix: 'build(dependencies)'
      prefix-development: 'build(dependencies)'
      include: 'scope'
    open-pull-requests-limit: 99
    versioning-strategy: 'increase'
